//! Admin Unix-domain socket and CLI dispatch.
//!
//! Two halves: a daemon-side accept loop ([`run_admin_loop`]) and a
//! CLI-side dispatcher ([`cli_dispatch`]) that opens the same socket
//! as a client. Both ends share the wire types so they stay in
//! lockstep.
//!
//! Wire protocol: line-delimited JSON. One request per connection,
//! one response, daemon closes. Request: `{"op":"…", …args}\n`.
//! Response: `{"ok":true, …fields}\n` or `{"ok":false,"error":"…",
//! "code":"…"}\n`. CR or embedded LF in any string field is rejected
//! the same way the git-credential parser rejects them
//! (Clone2Leak-class defense applied to the admin path too).
//!
//! State writes are atomic per PROTOCOLS.md § "Atomic writes":
//! tempfile → fsync → rename → fsync parent. `clients.json` lands
//! with mode `0o640`, the symbolon-owned `psks` file with `0o600`.
//! The daemon owns the PSK store directly — atomic write to disk
//! and in-memory swap happen in the same enroll/revoke handler.

use std::path::{Path, PathBuf};
use std::rc::Rc;
use std::time::Duration;

use compio::BufResult;
use compio::io::{AsyncRead, AsyncWrite, AsyncWriteExt};
use compio::net::{UnixListener, UnixStream};
use futures_util::FutureExt;
use serde::{Deserialize, Serialize};
use tracing::info;

use crate::daemon::{ResolvedClient, SharedState, StateMutationError};
use crate::events::EventKind;
use crate::identity::Identity;
use crate::ids::ReqId;
use crate::providers::{ProviderError, ProviderKind};
use crate::psk::Psk;

/// Admin requests are operator-driven JSON, not adversarial
/// throughput; the budget stays at 64 KiB to comfortably fit
/// human-typed enroll/revoke payloads. The daemon's wire path
/// uses a tighter 8 KiB budget for its slow-loris exposure.
const WIRE_READ_BUDGET: usize = 64 * 1024;
const PER_CONNECTION_TIMEOUT: Duration = Duration::from_secs(10);

// ---------------------------------------------------------------------------
// Wire types
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Serialize, Deserialize, strum::IntoStaticStr)]
#[serde(tag = "op", rename_all = "snake_case")]
#[strum(serialize_all = "snake_case")]
pub(crate) enum Request {
    Status,
    List,
    Enroll {
        provider: ProviderKind,
        client: String,
        #[serde(default)]
        note: Option<String>,
        /// Pre-generated by the CLI (either via `getrandom` or
        /// `--psk <hex>`).
        psk: Psk,
    },
    Revoke {
        provider: ProviderKind,
        client: String,
    },
    Mint {
        provider: ProviderKind,
        client: String,
        path: String,
    },
    Selfcheck {
        provider: ProviderKind,
    },
}

#[derive(Debug, Clone)]
pub enum CliCommand {
    Status,
    List,
    GithubEnroll {
        client: String,
        note: Option<String>,
        psk: Psk,
    },
    GithubRevoke {
        client: String,
    },
    GithubMint {
        client: String,
        path: String,
    },
    GithubSelfcheck,
}

impl CliCommand {
    fn to_request(&self) -> Request {
        match self {
            CliCommand::Status => Request::Status,
            CliCommand::List => Request::List,
            CliCommand::GithubEnroll { client, note, psk } => Request::Enroll {
                provider: ProviderKind::Github,
                client: client.clone(),
                note: note.clone(),
                psk: *psk,
            },
            CliCommand::GithubRevoke { client } => Request::Revoke {
                provider: ProviderKind::Github,
                client: client.clone(),
            },
            CliCommand::GithubMint { client, path } => Request::Mint {
                provider: ProviderKind::Github,
                client: client.clone(),
                path: path.clone(),
            },
            CliCommand::GithubSelfcheck => Request::Selfcheck {
                provider: ProviderKind::Github,
            },
        }
    }
}

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

#[derive(Debug, thiserror::Error)]
pub enum AdminError {
    #[error("admin socket bind failed at {}", path.display())]
    Bind {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("admin accept failed")]
    Accept(#[source] std::io::Error),
    #[error("failed to connect to admin socket at {}", path.display())]
    Connect {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("admin I/O error")]
    Io(#[source] std::io::Error),
    #[error("malformed admin request")]
    RequestParse(#[source] serde_json::Error),
    #[error("malformed admin response")]
    ResponseParse(#[source] serde_json::Error),
    #[error("admin response carried an error: {0}")]
    RemoteError(String),
    #[error("atomic write of {} failed", path.display())]
    AtomicWrite {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
}

// ---------------------------------------------------------------------------
// Daemon-side: accept loop
// ---------------------------------------------------------------------------

pub(crate) async fn run_admin_loop(
    listener: UnixListener,
    state: Rc<SharedState>,
) -> Result<(), AdminError> {
    // Cache effective UID once. Peer connections from this UID or
    // root are admitted; everything else is rejected with
    // evt=admin_denied. AGENTS.md invariant #9: the admin socket is
    // the sole admin surface, so this is the choke point.
    let my_uid = rustix::process::geteuid().as_raw();

    let tracker = crate::connection_tracker::ConnectionTracker::new(
        PER_CONNECTION_TIMEOUT,
        Duration::from_secs(5),
    );
    loop {
        // `select_biased!` with shutdown listed first: when both arms
        // are ready in the same iteration, shutdown wins. Closes the
        // "accept already ready + shutdown just fired" race without an
        // explicit `is_cancelled()` post-check inside the accept arm.
        futures_util::select_biased! {
            _ = state.shutdown.clone().wait().fuse() => break,
            accept_res = listener.accept().fuse() => {
                let (stream, _peer) = accept_res.map_err(AdminError::Accept)?;
                if !check_peer_uid(&stream, my_uid) {
                    continue;
                }
                let state = state.clone();
                // `req_id` carried via `tracing::Span` — `info!`/`warn!`
                // inside the handler inherits it via current-span.
                let span = tracing::info_span!("admin", req_id = %ReqId::new());
                tracker.spawn(async move || {
                    use tracing::Instrument;
                    handle_admin(stream, state).instrument(span).await;
                });
            }
        }
    }
    let _ = tracker.drain().await;
    Ok(())
}

async fn handle_admin(mut stream: UnixStream, state: Rc<SharedState>) {
    let raw = match read_line(&mut stream).await {
        Ok(bytes) if !bytes.is_empty() => bytes,
        _ => return,
    };
    let request: Request = match serde_json::from_slice(&raw) {
        Ok(r) => r,
        Err(e) => {
            info!(evt = %EventKind::AdminRequest, ok = false, error = %e);
            let resp = error_response("bad_request", &format!("request parse failed: {e}"));
            let _ = write_response(&mut stream, &resp).await;
            return;
        }
    };
    info!(evt = %EventKind::AdminRequest, op = <&str>::from(&request));
    let resp_value = match dispatch(&request, &state).await {
        Ok(v) => v,
        Err(e) => e,
    };
    let _ = write_response(&mut stream, &resp_value).await;
}

async fn dispatch(
    request: &Request,
    state: &Rc<SharedState>,
) -> Result<serde_json::Value, serde_json::Value> {
    match request {
        Request::Status => Ok(handle_status(state)),
        Request::List => Ok(handle_list(state)),
        Request::Enroll {
            provider,
            client,
            note,
            psk,
        } => handle_enroll(state, *provider, client, note.clone(), *psk).await,
        Request::Revoke { provider, client } => handle_revoke(state, *provider, client).await,
        Request::Mint {
            provider,
            client,
            path,
        } => handle_mint(state, *provider, client, path).await,
        Request::Selfcheck { provider } => handle_selfcheck(state, *provider).await,
    }
}

// ---------------------------------------------------------------------------
// Per-op handlers
// ---------------------------------------------------------------------------

fn handle_status(state: &SharedState) -> serde_json::Value {
    let uptime_sec = state.start_time.elapsed().as_secs();
    let mut providers: Vec<&str> = state.providers.values().map(|p| p.host()).collect();
    providers.sort();
    let client_count = state.clients.borrow().len();
    serde_json::json!({
        "ok": true,
        "uptime_sec": uptime_sec,
        "providers": providers,
        "client_count": client_count,
    })
}

fn handle_list(state: &SharedState) -> serde_json::Value {
    use time::format_description::well_known::Rfc3339;
    let borrowed = state.clients.borrow();
    let mut entries: Vec<(&Identity, &ResolvedClient)> = borrowed.iter().collect();
    entries.sort_by_key(|(id, _)| id.as_str());
    let entries: Vec<serde_json::Value> = entries
        .into_iter()
        .map(|(id, c)| {
            // Render providers via Display (matches the wire/file
            // form `"github"`) and sort for deterministic output.
            let mut provs: Vec<String> = c.providers.iter().map(ProviderKind::to_string).collect();
            provs.sort();
            serde_json::json!({
                "name": id.as_str(),
                "providers": provs,
                // `OffsetDateTime` formats deterministically via the
                // RFC 3339 well-known descriptor; `now_utc()`-sourced
                // values fall well within the supported year range.
                "enrolled_at": c.enrolled_at.format(&Rfc3339).expect("RFC3339 format of UTC datetime"),
                "note": c.note,
            })
        })
        .collect();
    serde_json::json!({ "ok": true, "clients": entries })
}

async fn handle_enroll(
    state: &SharedState,
    provider: ProviderKind,
    client: &str,
    note: Option<String>,
    psk: Psk,
) -> Result<serde_json::Value, serde_json::Value> {
    let identity = match Identity::parse(client) {
        Ok(id) => id,
        Err(_) => {
            return Err(error_response(
                "bad_request",
                "client name must be non-empty ASCII without ':' or whitespace",
            ));
        }
    };
    // PROTOCOLS.md "CR or embedded LF inside any string field is
    // rejected (same Clone2Leak-class defence applied to the admin
    // path)" — applies to `note` as well as `client`.
    if let Some(n) = note.as_deref()
        && n.bytes().any(|b| matches!(b, b'\r' | b'\n' | 0x00))
    {
        return Err(error_response(
            "bad_request",
            "note must not contain CR/LF/NUL bytes",
        ));
    }

    match state.enroll_client(identity, psk, provider, note).await {
        Ok(()) => {
            info!(evt = %EventKind::Enroll, provider = %provider, client = client);
            Ok(serde_json::json!({ "ok": true }))
        }
        Err(StateMutationError::ClientAlreadyEnrolled(c)) => Err(error_response(
            "client_already_enrolled",
            &format!("client '{c}' already enrolled"),
        )),
        Err(e) => Err(error_response("internal", &e.to_string())),
    }
}

async fn handle_revoke(
    state: &SharedState,
    provider: ProviderKind,
    client: &str,
) -> Result<serde_json::Value, serde_json::Value> {
    if state.lookup_provider(provider).is_none() {
        return Err(unknown_provider_error(provider));
    }
    match state.revoke_client(client).await {
        Ok(()) => Ok(serde_json::json!({ "ok": true })),
        Err(StateMutationError::UnknownClient(c)) => Err(error_response(
            "unknown_client",
            &format!("no enrolled client named '{c}'"),
        )),
        Err(e) => Err(error_response("internal", &e.to_string())),
    }
}

async fn handle_mint(
    state: &Rc<SharedState>,
    provider: ProviderKind,
    client: &str,
    path: &str,
) -> Result<serde_json::Value, serde_json::Value> {
    let provider = state
        .lookup_provider(provider)
        .ok_or_else(|| unknown_provider_error(provider))?;
    if !state.clients.borrow().contains_key(client) {
        return Err(error_response(
            "unknown_client",
            &format!("no enrolled client named '{client}'"),
        ));
    }
    match provider.mint(path).await {
        Ok(outcome) => Ok(serde_json::json!({
            "ok": true,
            "username": outcome.response.username,
            "password": outcome.response.password,
            "expires_at_unix": outcome.response.password_expiry_unix_secs(),
            "out_req_id": outcome.out_req_id,
            "provider_req_id": outcome.provider_req_id,
        })),
        Err(e) => Err(error_response_from_provider(&e)),
    }
}

async fn handle_selfcheck(
    state: &Rc<SharedState>,
    provider: ProviderKind,
) -> Result<serde_json::Value, serde_json::Value> {
    let provider = state
        .lookup_provider(provider)
        .ok_or_else(|| unknown_provider_error(provider))?;
    match provider.selfcheck().await {
        Ok(outcome) => Ok(serde_json::json!({
            "ok": true,
            "clock_skew_sec": outcome.clock_skew_sec,
            "out_req_id": outcome.out_req_id,
            "provider_req_id": outcome.provider_req_id,
            "details": outcome.details,
        })),
        Err(e) => Err(error_response_from_provider(&e)),
    }
}

fn error_response_from_provider(err: &ProviderError) -> serde_json::Value {
    let (code, msg) = match err {
        ProviderError::RepoNotFound => (
            "repo_not_accessible",
            "repository not found or credential lacks access".to_string(),
        ),
        ProviderError::Unauthorized { body } => ("provider_4xx", format!("unauthorized: {body}")),
        ProviderError::Forbidden { body } => ("provider_4xx", format!("forbidden: {body}")),
        ProviderError::RateLimited { retry_after } => (
            "provider_4xx",
            match retry_after {
                Some(d) => format!("rate limited (retry after {}s)", d.as_secs()),
                None => "rate limited".to_string(),
            },
        ),
        ProviderError::MalformedPath { path } => {
            ("bad_request", format!("malformed repository path: {path}"))
        }
        ProviderError::UnexpectedStatus { status } => {
            ("internal", format!("provider status {status}"))
        }
        // Transport / Timeout / Cancelled / MalformedResponse /
        // Internal all collapse to `internal`. The source chain is
        // walked by ErrorChain so the message includes the GitHub-
        // specific cause (ClientIdMismatch, JWT failures, etc.).
        _ => ("internal", format!("{}", crate::logging::ErrorChain(err))),
    };
    error_response(code, &msg)
}

// ---------------------------------------------------------------------------
// CLI-side: dispatch
// ---------------------------------------------------------------------------

pub async fn cli_dispatch(socket_path: &Path, command: CliCommand) -> Result<i32, AdminError> {
    let request = command.to_request();
    let mut payload = serde_json::to_vec(&request).map_err(AdminError::RequestParse)?;
    payload.push(b'\n');

    let mut stream =
        UnixStream::connect(socket_path)
            .await
            .map_err(|source| AdminError::Connect {
                path: socket_path.to_path_buf(),
                source,
            })?;
    let BufResult(write_res, _) = stream.write_all(payload).await;
    write_res.map_err(AdminError::Io)?;
    let _ = stream.flush().await;

    let response_bytes = read_line(&mut stream).await.map_err(AdminError::Io)?;
    let value: serde_json::Value =
        serde_json::from_slice(&response_bytes).map_err(AdminError::ResponseParse)?;

    if value.get("ok").and_then(|b| b.as_bool()) != Some(true) {
        let msg = value
            .get("error")
            .and_then(|s| s.as_str())
            .unwrap_or("(no error message)");
        eprintln!("symbolon: error: {msg}");
        return Ok(1);
    }

    command.print_success(&value);
    Ok(0)
}

/// Read a string field off a JSON response, falling back to `"?"`
/// for absent / non-string values. Used by the CLI printers, which
/// run after the daemon already validated the response.
fn json_str_or_q<'a>(v: &'a serde_json::Value, k: &str) -> &'a str {
    v.get(k).and_then(|x| x.as_str()).unwrap_or("?")
}

/// Read a u64 field off a JSON response, falling back to `0`.
fn json_u64_or_zero(v: &serde_json::Value, k: &str) -> u64 {
    v.get(k).and_then(|x| x.as_u64()).unwrap_or(0)
}

/// Read a string-array field and join with `sep`. Empty on absent
/// or non-array; non-string elements are filtered out.
fn json_str_array_join(v: &serde_json::Value, k: &str, sep: &str) -> String {
    v.get(k)
        .and_then(|x| x.as_array())
        .map(|arr| {
            arr.iter()
                .filter_map(|x| x.as_str())
                .collect::<Vec<_>>()
                .join(sep)
        })
        .unwrap_or_default()
}

impl CliCommand {
    fn print_success(&self, response: &serde_json::Value) {
        match self {
            CliCommand::Status => {
                println!("Uptime: {}s", json_u64_or_zero(response, "uptime_sec"));
                println!(
                    "Providers: {}",
                    json_str_array_join(response, "providers", ", ")
                );
                println!("Clients: {}", json_u64_or_zero(response, "client_count"));
            }
            CliCommand::List => {
                let empty = vec![];
                let entries = response
                    .get("clients")
                    .and_then(|v| v.as_array())
                    .unwrap_or(&empty);
                if entries.is_empty() {
                    println!("(no enrolled clients)");
                    return;
                }
                for c in entries {
                    println!(
                        "{}\t{}\t{}",
                        json_str_or_q(c, "name"),
                        json_str_array_join(c, "providers", ","),
                        json_str_or_q(c, "enrolled_at")
                    );
                }
            }
            CliCommand::GithubEnroll { psk, .. } => {
                // Stdout is just the 64 hex chars — pipe-friendly
                // (`symbolon github enroll vm-1 | ssh client 'cat > /etc/symbolon/psk'`).
                // The PSK is one we generated locally (or one the
                // operator supplied via `--psk`); daemon response is
                // a bare `{"ok": true}` ack.
                let hex = psk.to_hex();
                println!(
                    "{}",
                    std::str::from_utf8(&hex).expect("Psk::to_hex is ASCII")
                );
            }
            CliCommand::GithubRevoke { client } => {
                println!("Revoked '{client}' from github.com.");
            }
            CliCommand::GithubMint { .. } => {
                println!("username={}", json_str_or_q(response, "username"));
                println!("password={}", json_str_or_q(response, "password"));
                println!(
                    "expires_at_unix={}",
                    json_u64_or_zero(response, "expires_at_unix")
                );
            }
            CliCommand::GithubSelfcheck => {
                // Provider-specific fields nest under `details` per
                // PROVIDER_CONTRACT.md § A3 — only the abstract fields
                // (`clock_skew_sec`, `provider_req_id`, `out_req_id`)
                // live at the top level.
                let details = response.get("details").unwrap_or(&serde_json::Value::Null);
                let skew = response
                    .get("clock_skew_sec")
                    .and_then(|v| v.as_i64())
                    .unwrap_or(0);
                println!(
                    "OK: App {} reachable at {}, clock skew {skew}s",
                    json_str_or_q(details, "client_id"),
                    json_str_or_q(details, "api_base"),
                );
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn error_response(code: &str, msg: &str) -> serde_json::Value {
    serde_json::json!({ "ok": false, "code": code, "error": msg })
}

fn unknown_provider_error(provider: ProviderKind) -> serde_json::Value {
    error_response(
        "unknown_provider",
        &format!("provider '{provider}' not configured"),
    )
}

// Returns false (denial) only on a definitive non-root, non-self UID.
// On `socket_peercred` syscall failure we admit the connection and
// log; refusing on syscall error would be a denial-of-service
// against the operator if the kernel ever returns a transient EINVAL
// or similar.
fn check_peer_uid(stream: &UnixStream, my_uid: u32) -> bool {
    use std::os::fd::AsFd;
    match rustix::net::sockopt::socket_peercred(stream.as_fd()) {
        Ok(cred) => {
            let uid = cred.uid.as_raw();
            if uid == 0 || uid == my_uid {
                true
            } else {
                tracing::warn!(
                    evt = %EventKind::AdminDenied,
                    peer_uid = uid,
                    peer_pid = cred.pid.as_raw_nonzero().get(),
                );
                false
            }
        }
        Err(e) => {
            tracing::warn!(
                evt = %EventKind::AdminPeercredFailed,
                error = %e,
                "admitting connection; peer credentials unavailable",
            );
            true
        }
    }
}

async fn read_line(stream: &mut UnixStream) -> std::io::Result<Vec<u8>> {
    let mut accumulated = Vec::new();
    let mut chunk: Vec<u8> = Vec::with_capacity(1024);
    loop {
        if let Some(pos) = accumulated.iter().position(|&b| b == b'\n') {
            accumulated.truncate(pos);
            return Ok(accumulated);
        }
        if accumulated.len() >= WIRE_READ_BUDGET {
            return Err(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                "admin request exceeds size cap",
            ));
        }
        chunk.clear();
        let BufResult(res, returned) = stream.read(chunk).await;
        chunk = returned;
        match res {
            Ok(0) => {
                // EOF without a trailing `\n`. Caller treats this as a
                // bad request rather than an empty line.
                return Err(std::io::Error::new(
                    std::io::ErrorKind::UnexpectedEof,
                    "admin connection closed mid-request",
                ));
            }
            Ok(_) => accumulated.extend_from_slice(&chunk),
            Err(e) => return Err(e),
        }
    }
}

async fn write_response(stream: &mut UnixStream, value: &serde_json::Value) -> std::io::Result<()> {
    let mut payload = serde_json::to_vec(value).map_err(std::io::Error::other)?;
    payload.push(b'\n');
    let BufResult(res, _) = stream.write_all(payload).await;
    res?;
    let _ = stream.flush().await;
    Ok(())
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn request_round_trips() {
        let r = Request::Enroll {
            provider: ProviderKind::Github,
            client: "vm-1".to_string(),
            note: None,
            psk: crate::psk::Psk::from([0xAAu8; 32]),
        };
        let s = serde_json::to_string(&r).unwrap();
        let back: Request = serde_json::from_str(&s).unwrap();
        match back {
            Request::Enroll {
                provider, client, ..
            } => {
                assert_eq!(provider, ProviderKind::Github);
                assert_eq!(client, "vm-1");
            }
            _ => panic!("wrong variant"),
        }
    }

    #[test]
    fn status_request_serializes_to_op_field() {
        let s = serde_json::to_string(&Request::Status).unwrap();
        assert!(s.contains("\"op\":\"status\""));
    }

    #[test]
    fn error_response_shape() {
        let e = error_response("bad_request", "nope");
        assert_eq!(e["ok"], serde_json::json!(false));
        assert_eq!(e["code"], "bad_request");
        assert_eq!(e["error"], "nope");
    }
}
